env:
  browser: true
  es2021: true
  node: true
extends:
  - prettier/@typescript-eslint
  - plugin:prettier/recommended
  - plugin:vue/essential
  - plugin:vue/vue3-essential
  - "@vue/typescript"
parser: vue-eslint-parser
parserOptions:
  parser: "@typescript-eslint/parser"
  ecmaVersion: 2020
  sourceType: module
plugins:
  - "@typescript-eslint"
rules:
  "@typescript-eslint/member-delimiter-style":
    - error
    - multiline:
        delimiter: none
        requireLast: false
      singleline:
        delimiter: comma
        requireLast: false
  vue/no-multiple-template-root: "off"
