on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Build
    timeout-minutes: 20
    runs-on: ubuntu-latest
    env:
      # NODE_OPTIONS: "--max-old-space-size=16384"
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Check Code Formatting
        run: pnpm lint

      - name: Run Component Tests
        run:
          pnpm test:ci && pnpm cy:run --component --record --key
          $CYPRESS_COMPONENT_TESTING_KEY
        env:
          CYPRESS_COMPONENT_TESTING_KEY:
            ${{ secrets.CYPRESS_COMPONENT_TESTING_KEY }}
          CI: true

      - name: Build packages
        run: pnpm build:ci
